[package]
name = "distream"
version = "0.1.0"
edition = "2024"

[dependencies]
srt-tokio = "0.4.4"
sha2 = "0.11.0-rc.3"

[dependencies.tokio]
features = ["full", "net", "time", "test-util", "macros", "io-util", "io-std", "sync"]
version = "1"

[dependencies.tokio-stream]
features = ["sync"]
version = "0.1"
